### ISSUE TITLE
Album Captions/Playcount settings sometimes ingnored

### ISSUE THREAD

**Issue by tguser13** [Irishsmurf/LastFM-PHP-Album-Collage#13]
Reconstruct the error by open the following links in this order one by one (in another tab) AFTER each image is fully loaded.
Then compare the link and the result.

http://lastfm.paddez.com/lastfm.php?user=GreyComa&period=7day&cols=3&rows=3&info=&playcount=
http://lastfm.paddez.com/lastfm.php?user=GreyComa&period=7day&cols=3&rows=3&info=&playcount=1
http://lastfm.paddez.com/lastfm.php?user=GreyComa&period=7day&cols=3&rows=3&info=1&playcount=1
http://lastfm.paddez.com/lastfm.php?user=GreyComa&period=7day&cols=3&rows=3&info=1&playcount=

**Comment by Irishsmurf** [comment]
Cheers man, this was basically because I didn't vary on Playcount/Album info.

Should be fixed now!
